yml: silence unused variable warning with Clang 13
yml.c:383:9: error: variable 'indent' set but not used [-Werror,-Wunused-but-set-variable]
    int indent = 0;
        ^